/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "ActiveRequestTable.h"

static asn_TYPE_member_t asn_MBR_ActiveRequestTable_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, priorityReqEntryNum),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RequestEntry,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"priorityReqEntryNum"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, priorityReqID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"priorityReqID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, priorityActive),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ActivePriority,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"priorityActive"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, type),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NTCIPVehicleClass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, inLane),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"inLane"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, outLane),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"outLane"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, priorityReqTimeOfSrvDesd),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSecond,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"priorityReqTimeOfSrvDesd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, priorityReqTimeOfEstdDepart),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSecond,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"priorityReqTimeOfEstdDepart"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, requestState),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, requestSeqNumber),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestSeqNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, priorityReqTimeOfMsg),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSecond,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"priorityReqTimeOfMsg"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveRequestTable, priorityReqTimeToLive),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSecond,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"priorityReqTimeToLive"
		},
};
static ber_tlv_tag_t asn_DEF_ActiveRequestTable_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ActiveRequestTable_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* priorityReqEntryNum at 36 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* priorityReqID at 37 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* priorityActive at 38 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* type at 39 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* inLane at 40 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* outLane at 41 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* priorityReqTimeOfSrvDesd at 42 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* priorityReqTimeOfEstdDepart at 43 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* requestState at 44 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* requestSeqNumber at 45 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* priorityReqTimeOfMsg at 46 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* priorityReqTimeToLive at 48 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ActiveRequestTable_specs_1 = {
	sizeof(struct ActiveRequestTable),
	offsetof(struct ActiveRequestTable, _asn_ctx),
	asn_MAP_ActiveRequestTable_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ActiveRequestTable = {
	"ActiveRequestTable",
	"ActiveRequestTable",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ActiveRequestTable_tags_1,
	sizeof(asn_DEF_ActiveRequestTable_tags_1)
		/sizeof(asn_DEF_ActiveRequestTable_tags_1[0]), /* 1 */
	asn_DEF_ActiveRequestTable_tags_1,	/* Same as above */
	sizeof(asn_DEF_ActiveRequestTable_tags_1)
		/sizeof(asn_DEF_ActiveRequestTable_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ActiveRequestTable_1,
	12,	/* Elements count */
	&asn_SPC_ActiveRequestTable_specs_1	/* Additional specs */
};

