/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "BSM.txt"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "BSM.h"

static int
msgID_2_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
msgID_2_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
msgID_2_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	msgID_2_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
msgID_2_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	msgID_2_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
msgID_2_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	msgID_2_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
msgID_2_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	msgID_2_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
msgID_2_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	msgID_2_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
msgID_2_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	msgID_2_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
memb_bsmBlob_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 38)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_INTEGER_enum_map_t asn_MAP_msgID_value2enum_2[] = {
	{ 0,	8,	"reserved" },
	{ 1,	15,	"alaCarteMessage" },
	{ 2,	18,	"basicSafetyMessage" },
	{ 3,	25,	"basicSafetyMessageVerbose" },
	{ 4,	19,	"commonSafetyRequest" },
	{ 5,	21,	"emergencyVehicleAlert" },
	{ 6,	26,	"intersectionCollisionAlert" },
	{ 7,	7,	"mapData" },
	{ 8,	15,	"nmeaCorrections" },
	{ 9,	19,	"probeDataManagement" },
	{ 10,	16,	"probeVehicleData" },
	{ 11,	13,	"roadSideAlert" },
	{ 12,	15,	"rtcmCorrections" },
	{ 13,	27,	"signalPhaseAndTimingMessage" },
	{ 14,	20,	"signalRequestMessage" },
	{ 15,	19,	"signalStatusMessage" },
	{ 16,	19,	"travelerInformation" }
};
static unsigned int asn_MAP_msgID_enum2value_2[] = {
	1,	/* alaCarteMessage(1) */
	2,	/* basicSafetyMessage(2) */
	3,	/* basicSafetyMessageVerbose(3) */
	4,	/* commonSafetyRequest(4) */
	5,	/* emergencyVehicleAlert(5) */
	6,	/* intersectionCollisionAlert(6) */
	7,	/* mapData(7) */
	8,	/* nmeaCorrections(8) */
	9,	/* probeDataManagement(9) */
	10,	/* probeVehicleData(10) */
	0,	/* reserved(0) */
	11,	/* roadSideAlert(11) */
	12,	/* rtcmCorrections(12) */
	13,	/* signalPhaseAndTimingMessage(13) */
	14,	/* signalRequestMessage(14) */
	15,	/* signalStatusMessage(15) */
	16	/* travelerInformation(16) */
};
static asn_INTEGER_specifics_t asn_SPC_msgID_specs_2 = {
	asn_MAP_msgID_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_msgID_enum2value_2,	/* N => "tag"; sorted by N */
	17,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1	/* Strict enumeration */
};
static ber_tlv_tag_t asn_DEF_msgID_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_msgID_2 = {
	"msgID",
	"msgID",
	msgID_2_free,
	msgID_2_print,
	msgID_2_constraint,
	msgID_2_decode_ber,
	msgID_2_encode_der,
	msgID_2_decode_xer,
	msgID_2_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_msgID_tags_2,
	sizeof(asn_DEF_msgID_tags_2)
		/sizeof(asn_DEF_msgID_tags_2[0]) - 1, /* 1 */
	asn_DEF_msgID_tags_2,	/* Same as above */
	sizeof(asn_DEF_msgID_tags_2)
		/sizeof(asn_DEF_msgID_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_msgID_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_BSM_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BSM, msgID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_msgID_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msgID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BSM, bsmBlob),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_bsmBlob_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bsmBlob"
		},
};
static ber_tlv_tag_t asn_DEF_BSM_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BSM_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msgID at 6 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* bsmBlob at 24 */
};
static asn_SEQUENCE_specifics_t asn_SPC_BSM_specs_1 = {
	sizeof(struct BSM),
	offsetof(struct BSM, _asn_ctx),
	asn_MAP_BSM_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BSM = {
	"BSM",
	"BSM",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BSM_tags_1,
	sizeof(asn_DEF_BSM_tags_1)
		/sizeof(asn_DEF_BSM_tags_1[0]), /* 1 */
	asn_DEF_BSM_tags_1,	/* Same as above */
	sizeof(asn_DEF_BSM_tags_1)
		/sizeof(asn_DEF_BSM_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BSM_1,
	2,	/* Elements count */
	&asn_SPC_BSM_specs_1	/* Additional specs */
};

