/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "VehicleIdent.h"

static int check_permitted_alphabet_4(const void *sptr) {
	/* The underlying type is IA5String */
	const IA5String_t *st = (const IA5String_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv <= 127)) return -1;
	}
	return 0;
}

static int
vGroup_8_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
vGroup_8_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
vGroup_8_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	vGroup_8_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
vGroup_8_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	vGroup_8_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
vGroup_8_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	vGroup_8_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
vGroup_8_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	vGroup_8_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
vGroup_8_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	vGroup_8_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
vGroup_8_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	vGroup_8_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
rGroup_45_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
rGroup_45_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
rGroup_45_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	rGroup_45_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
rGroup_45_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	rGroup_45_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
rGroup_45_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	rGroup_45_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
rGroup_45_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	rGroup_45_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
rGroup_45_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	rGroup_45_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
rGroup_45_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	rGroup_45_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
rEquip_61_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
rEquip_61_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
rEquip_61_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	rEquip_61_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
rEquip_61_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	rEquip_61_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
rEquip_61_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	rEquip_61_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
rEquip_61_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	rEquip_61_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
rEquip_61_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	rEquip_61_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
rEquip_61_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	rEquip_61_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
memb_ownerCode_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const IA5String_t *st = (const IA5String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 32)
		 && !check_permitted_alphabet_4(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_INTEGER_enum_map_t asn_MAP_vGroup_value2enum_8[] = {
	{ 9217,	12,	"all-vehicles" },
	{ 9218,	8,	"bicycles" },
	{ 9219,	11,	"motorcycles" },
	{ 9220,	4,	"cars" },
	{ 9221,	14,	"light-vehicles" },
	{ 9222,	23,	"cars-and-light-vehicles" },
	{ 9223,	18,	"cars-with-trailers" },
	{ 9224,	31,	"cars-with-recreational-trailers" },
	{ 9225,	22,	"vehicles-with-trailers" },
	{ 9226,	14,	"heavy-vehicles" },
	{ 9227,	6,	"trucks" },
	{ 9228,	5,	"buses" },
	{ 9229,	17,	"articulated-buses" },
	{ 9230,	12,	"school-buses" },
	{ 9231,	27,	"vehicles-with-semi-trailers" },
	{ 9232,	29,	"vehicles-with-double-trailers" },
	{ 9233,	21,	"high-profile-vehicles" },
	{ 9234,	13,	"wide-vehicles" },
	{ 9235,	13,	"long-vehicles" },
	{ 9236,	15,	"hazardous-loads" },
	{ 9237,	17,	"exceptional-loads" },
	{ 9238,	14,	"abnormal-loads" },
	{ 9239,	7,	"convoys" },
	{ 9240,	20,	"maintenance-vehicles" },
	{ 9241,	17,	"delivery-vehicles" },
	{ 9242,	42,	"vehicles-with-even-numbered-license-plates" },
	{ 9243,	41,	"vehicles-with-odd-numbered-license-plates" },
	{ 9244,	29,	"vehicles-with-parking-permits" },
	{ 9245,	34,	"vehicles-with-catalytic-converters" },
	{ 9246,	37,	"vehicles-without-catalytic-converters" },
	{ 9247,	20,	"gas-powered-vehicles" },
	{ 9248,	23,	"diesel-powered-vehicles" },
	{ 9249,	12,	"lPG-vehicles" },
	{ 9250,	16,	"military-convoys" },
	{ 9251,	17,	"military-vehicles" }
	/* This list is extensible */
};
static unsigned int asn_MAP_vGroup_enum2value_8[] = {
	21,	/* abnormal-loads(9238) */
	0,	/* all-vehicles(9217) */
	12,	/* articulated-buses(9229) */
	1,	/* bicycles(9218) */
	11,	/* buses(9228) */
	3,	/* cars(9220) */
	5,	/* cars-and-light-vehicles(9222) */
	7,	/* cars-with-recreational-trailers(9224) */
	6,	/* cars-with-trailers(9223) */
	22,	/* convoys(9239) */
	24,	/* delivery-vehicles(9241) */
	31,	/* diesel-powered-vehicles(9248) */
	20,	/* exceptional-loads(9237) */
	30,	/* gas-powered-vehicles(9247) */
	19,	/* hazardous-loads(9236) */
	9,	/* heavy-vehicles(9226) */
	16,	/* high-profile-vehicles(9233) */
	32,	/* lPG-vehicles(9249) */
	4,	/* light-vehicles(9221) */
	18,	/* long-vehicles(9235) */
	23,	/* maintenance-vehicles(9240) */
	33,	/* military-convoys(9250) */
	34,	/* military-vehicles(9251) */
	2,	/* motorcycles(9219) */
	13,	/* school-buses(9230) */
	10,	/* trucks(9227) */
	28,	/* vehicles-with-catalytic-converters(9245) */
	15,	/* vehicles-with-double-trailers(9232) */
	25,	/* vehicles-with-even-numbered-license-plates(9242) */
	26,	/* vehicles-with-odd-numbered-license-plates(9243) */
	27,	/* vehicles-with-parking-permits(9244) */
	14,	/* vehicles-with-semi-trailers(9231) */
	8,	/* vehicles-with-trailers(9225) */
	29,	/* vehicles-without-catalytic-converters(9246) */
	17	/* wide-vehicles(9234) */
	/* This list is extensible */
};
static asn_INTEGER_specifics_t asn_SPC_vGroup_specs_8 = {
	asn_MAP_vGroup_value2enum_8,	/* "tag" => N; sorted by tag */
	asn_MAP_vGroup_enum2value_8,	/* N => "tag"; sorted by N */
	35,	/* Number of elements in the maps */
	36,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_vGroup_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_vGroup_8 = {
	"vGroup",
	"vGroup",
	vGroup_8_free,
	vGroup_8_print,
	vGroup_8_constraint,
	vGroup_8_decode_ber,
	vGroup_8_encode_der,
	vGroup_8_decode_xer,
	vGroup_8_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_vGroup_tags_8,
	sizeof(asn_DEF_vGroup_tags_8)
		/sizeof(asn_DEF_vGroup_tags_8[0]) - 1, /* 1 */
	asn_DEF_vGroup_tags_8,	/* Same as above */
	sizeof(asn_DEF_vGroup_tags_8)
		/sizeof(asn_DEF_vGroup_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_vGroup_specs_8	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_rGroup_value2enum_45[] = {
	{ 9729,	23,	"emergency-vehicle-units" },
	{ 9730,	29,	"federal-law-enforcement-units" },
	{ 9731,	18,	"state-police-units" },
	{ 9732,	19,	"county-police-units" },
	{ 9733,	18,	"local-police-units" },
	{ 9734,	15,	"ambulance-units" },
	{ 9735,	12,	"rescue-units" },
	{ 9736,	10,	"fire-units" },
	{ 9737,	12,	"hAZMAT-units" },
	{ 9738,	14,	"light-tow-unit" },
	{ 9739,	14,	"heavy-tow-unit" },
	{ 9740,	23,	"freeway-service-patrols" },
	{ 9741,	29,	"transportation-response-units" },
	{ 9742,	33,	"private-contractor-response-units" }
	/* This list is extensible */
};
static unsigned int asn_MAP_rGroup_enum2value_45[] = {
	5,	/* ambulance-units(9734) */
	3,	/* county-police-units(9732) */
	0,	/* emergency-vehicle-units(9729) */
	1,	/* federal-law-enforcement-units(9730) */
	7,	/* fire-units(9736) */
	11,	/* freeway-service-patrols(9740) */
	8,	/* hAZMAT-units(9737) */
	10,	/* heavy-tow-unit(9739) */
	9,	/* light-tow-unit(9738) */
	4,	/* local-police-units(9733) */
	13,	/* private-contractor-response-units(9742) */
	6,	/* rescue-units(9735) */
	2,	/* state-police-units(9731) */
	12	/* transportation-response-units(9741) */
	/* This list is extensible */
};
static asn_INTEGER_specifics_t asn_SPC_rGroup_specs_45 = {
	asn_MAP_rGroup_value2enum_45,	/* "tag" => N; sorted by tag */
	asn_MAP_rGroup_enum2value_45,	/* N => "tag"; sorted by N */
	14,	/* Number of elements in the maps */
	15,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_rGroup_tags_45[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rGroup_45 = {
	"rGroup",
	"rGroup",
	rGroup_45_free,
	rGroup_45_print,
	rGroup_45_constraint,
	rGroup_45_decode_ber,
	rGroup_45_encode_der,
	rGroup_45_decode_xer,
	rGroup_45_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_rGroup_tags_45,
	sizeof(asn_DEF_rGroup_tags_45)
		/sizeof(asn_DEF_rGroup_tags_45[0]) - 1, /* 1 */
	asn_DEF_rGroup_tags_45,	/* Same as above */
	sizeof(asn_DEF_rGroup_tags_45)
		/sizeof(asn_DEF_rGroup_tags_45[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_rGroup_specs_45	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_rEquip_value2enum_61[] = {
	{ 9985,	23,	"ground-fire-suppression" },
	{ 9986,	22,	"heavy-ground-equipment" },
	{ 9988,	8,	"aircraft" },
	{ 9989,	16,	"marine-equipment" },
	{ 9990,	17,	"support-equipment" },
	{ 9991,	19,	"medical-rescue-unit" },
	{ 9993,	5,	"other" },
	{ 9994,	29,	"ground-fire-suppression-other" },
	{ 9995,	6,	"engine" },
	{ 9996,	15,	"truck-or-aerial" },
	{ 9997,	5,	"quint" },
	{ 9998,	25,	"tanker-pumper-combination" },
	{ 10000,	11,	"brush-truck" },
	{ 10001,	28,	"aircraft-rescue-firefighting" },
	{ 10004,	28,	"heavy-ground-equipment-other" },
	{ 10005,	13,	"dozer-or-plow" },
	{ 10006,	7,	"tractor" },
	{ 10008,	16,	"tanker-or-tender" },
	{ 10024,	14,	"aircraft-other" },
	{ 10025,	26,	"aircraft-fixed-wing-tanker" },
	{ 10026,	10,	"helitanker" },
	{ 10027,	10,	"helicopter" },
	{ 10034,	22,	"marine-equipment-other" },
	{ 10035,	19,	"fire-boat-with-pump" },
	{ 10036,	12,	"boat-no-pump" },
	{ 10044,	23,	"support-apparatus-other" },
	{ 10045,	27,	"breathing-apparatus-support" },
	{ 10046,	18,	"light-and-air-unit" },
	{ 10054,	25,	"medical-rescue-unit-other" },
	{ 10055,	11,	"rescue-unit" },
	{ 10056,	24,	"urban-search-rescue-unit" },
	{ 10057,	17,	"high-angle-rescue" },
	{ 10058,	17,	"crash-fire-rescue" },
	{ 10059,	8,	"bLS-unit" },
	{ 10060,	8,	"aLS-unit" },
	{ 10075,	19,	"mobile-command-post" },
	{ 10076,	17,	"chief-officer-car" },
	{ 10077,	11,	"hAZMAT-unit" },
	{ 10078,	16,	"type-i-hand-crew" },
	{ 10079,	17,	"type-ii-hand-crew" },
	{ 10083,	23,	"privately-owned-vehicle" },
	{ 10084,	24,	"other-apparatus-resource" },
	{ 10085,	9,	"ambulance" },
	{ 10086,	14,	"bomb-squad-van" },
	{ 10087,	17,	"combine-harvester" },
	{ 10088,	20,	"construction-vehicle" },
	{ 10089,	12,	"farm-tractor" },
	{ 10090,	22,	"grass-cutting-machines" },
	{ 10091,	22,	"hAZMAT-containment-tow" },
	{ 10092,	9,	"heavy-tow" },
	{ 10093,	22,	"hedge-cutting-machines" },
	{ 10094,	9,	"light-tow" },
	{ 10095,	12,	"mobile-crane" },
	{ 10096,	25,	"refuse-collection-vehicle" },
	{ 10097,	19,	"resurfacing-vehicle" },
	{ 10098,	12,	"road-sweeper" },
	{ 10099,	32,	"roadside-litter-collection-crews" },
	{ 10100,	15,	"salvage-vehicle" },
	{ 10101,	10,	"sand-truck" },
	{ 10102,	8,	"snowplow" },
	{ 10103,	12,	"steam-roller" },
	{ 10104,	13,	"swat-team-van" },
	{ 10105,	20,	"track-laying-vehicle" },
	{ 10106,	15,	"unknown-vehicle" },
	{ 10107,	20,	"white-lining-vehicle" },
	{ 10108,	10,	"dump-truck" },
	{ 10109,	18,	"supervisor-vehicle" },
	{ 10110,	11,	"snow-blower" },
	{ 10111,	18,	"rotary-snow-blower" },
	{ 10112,	11,	"road-grader" },
	{ 10113,	11,	"steam-truck" },
	{ 10114,	11,	"flatbed-tow" }
	/* This list is extensible */
};
static unsigned int asn_MAP_rEquip_enum2value_61[] = {
	34,	/* aLS-unit(10060) */
	2,	/* aircraft(9988) */
	19,	/* aircraft-fixed-wing-tanker(10025) */
	18,	/* aircraft-other(10024) */
	13,	/* aircraft-rescue-firefighting(10001) */
	42,	/* ambulance(10085) */
	33,	/* bLS-unit(10059) */
	24,	/* boat-no-pump(10036) */
	43,	/* bomb-squad-van(10086) */
	26,	/* breathing-apparatus-support(10045) */
	12,	/* brush-truck(10000) */
	36,	/* chief-officer-car(10076) */
	44,	/* combine-harvester(10087) */
	45,	/* construction-vehicle(10088) */
	32,	/* crash-fire-rescue(10058) */
	15,	/* dozer-or-plow(10005) */
	65,	/* dump-truck(10108) */
	8,	/* engine(9995) */
	46,	/* farm-tractor(10089) */
	23,	/* fire-boat-with-pump(10035) */
	71,	/* flatbed-tow(10114) */
	47,	/* grass-cutting-machines(10090) */
	0,	/* ground-fire-suppression(9985) */
	7,	/* ground-fire-suppression-other(9994) */
	48,	/* hAZMAT-containment-tow(10091) */
	37,	/* hAZMAT-unit(10077) */
	1,	/* heavy-ground-equipment(9986) */
	14,	/* heavy-ground-equipment-other(10004) */
	49,	/* heavy-tow(10092) */
	50,	/* hedge-cutting-machines(10093) */
	21,	/* helicopter(10027) */
	20,	/* helitanker(10026) */
	31,	/* high-angle-rescue(10057) */
	27,	/* light-and-air-unit(10046) */
	51,	/* light-tow(10094) */
	3,	/* marine-equipment(9989) */
	22,	/* marine-equipment-other(10034) */
	5,	/* medical-rescue-unit(9991) */
	28,	/* medical-rescue-unit-other(10054) */
	35,	/* mobile-command-post(10075) */
	52,	/* mobile-crane(10095) */
	6,	/* other(9993) */
	41,	/* other-apparatus-resource(10084) */
	40,	/* privately-owned-vehicle(10083) */
	10,	/* quint(9997) */
	53,	/* refuse-collection-vehicle(10096) */
	29,	/* rescue-unit(10055) */
	54,	/* resurfacing-vehicle(10097) */
	69,	/* road-grader(10112) */
	55,	/* road-sweeper(10098) */
	56,	/* roadside-litter-collection-crews(10099) */
	68,	/* rotary-snow-blower(10111) */
	57,	/* salvage-vehicle(10100) */
	58,	/* sand-truck(10101) */
	67,	/* snow-blower(10110) */
	59,	/* snowplow(10102) */
	60,	/* steam-roller(10103) */
	70,	/* steam-truck(10113) */
	66,	/* supervisor-vehicle(10109) */
	25,	/* support-apparatus-other(10044) */
	4,	/* support-equipment(9990) */
	61,	/* swat-team-van(10104) */
	17,	/* tanker-or-tender(10008) */
	11,	/* tanker-pumper-combination(9998) */
	62,	/* track-laying-vehicle(10105) */
	16,	/* tractor(10006) */
	9,	/* truck-or-aerial(9996) */
	38,	/* type-i-hand-crew(10078) */
	39,	/* type-ii-hand-crew(10079) */
	63,	/* unknown-vehicle(10106) */
	30,	/* urban-search-rescue-unit(10056) */
	64	/* white-lining-vehicle(10107) */
	/* This list is extensible */
};
static asn_INTEGER_specifics_t asn_SPC_rEquip_specs_61 = {
	asn_MAP_rEquip_value2enum_61,	/* "tag" => N; sorted by tag */
	asn_MAP_rEquip_enum2value_61,	/* N => "tag"; sorted by N */
	72,	/* Number of elements in the maps */
	73,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_rEquip_tags_61[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rEquip_61 = {
	"rEquip",
	"rEquip",
	rEquip_61_free,
	rEquip_61_print,
	rEquip_61_constraint,
	rEquip_61_decode_ber,
	rEquip_61_encode_der,
	rEquip_61_decode_xer,
	rEquip_61_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_rEquip_tags_61,
	sizeof(asn_DEF_rEquip_tags_61)
		/sizeof(asn_DEF_rEquip_tags_61[0]) - 1, /* 1 */
	asn_DEF_rEquip_tags_61,	/* Same as above */
	sizeof(asn_DEF_rEquip_tags_61)
		/sizeof(asn_DEF_rEquip_tags_61[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_rEquip_specs_61	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_vehicleClass_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct vehicleClass, choice.vGroup),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_vGroup_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vGroup"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct vehicleClass, choice.rGroup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_rGroup_45,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rGroup"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct vehicleClass, choice.rEquip),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_rEquip_61,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rEquip"
		},
};
static asn_TYPE_tag2member_t asn_MAP_vehicleClass_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vGroup at 99 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rGroup at 136 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* rEquip at 154 */
};
static asn_CHOICE_specifics_t asn_SPC_vehicleClass_specs_7 = {
	sizeof(struct vehicleClass),
	offsetof(struct vehicleClass, _asn_ctx),
	offsetof(struct vehicleClass, present),
	sizeof(((struct vehicleClass *)0)->present),
	asn_MAP_vehicleClass_tag2el_7,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_vehicleClass_7 = {
	"vehicleClass",
	"vehicleClass",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_vehicleClass_7,
	3,	/* Elements count */
	&asn_SPC_vehicleClass_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_VehicleIdent_1[] = {
	{ ATF_POINTER, 6, offsetof(struct VehicleIdent, name),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DescriptiveName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_POINTER, 5, offsetof(struct VehicleIdent, vin),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VINstring,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vin"
		},
	{ ATF_POINTER, 4, offsetof(struct VehicleIdent, ownerCode),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		memb_ownerCode_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ownerCode"
		},
	{ ATF_POINTER, 3, offsetof(struct VehicleIdent, id),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TemporaryID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"id"
		},
	{ ATF_POINTER, 2, offsetof(struct VehicleIdent, vehicleType),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleType"
		},
	{ ATF_POINTER, 1, offsetof(struct VehicleIdent, vehicleClass),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_vehicleClass_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleClass"
		},
};
static ber_tlv_tag_t asn_DEF_VehicleIdent_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_VehicleIdent_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* name at 87 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* vin at 89 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ownerCode at 91 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* id at 93 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* vehicleType at 95 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* vehicleClass at 134 */
};
static asn_SEQUENCE_specifics_t asn_SPC_VehicleIdent_specs_1 = {
	sizeof(struct VehicleIdent),
	offsetof(struct VehicleIdent, _asn_ctx),
	asn_MAP_VehicleIdent_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_VehicleIdent = {
	"VehicleIdent",
	"VehicleIdent",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VehicleIdent_tags_1,
	sizeof(asn_DEF_VehicleIdent_tags_1)
		/sizeof(asn_DEF_VehicleIdent_tags_1[0]), /* 1 */
	asn_DEF_VehicleIdent_tags_1,	/* Same as above */
	sizeof(asn_DEF_VehicleIdent_tags_1)
		/sizeof(asn_DEF_VehicleIdent_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_VehicleIdent_1,
	6,	/* Elements count */
	&asn_SPC_VehicleIdent_specs_1	/* Additional specs */
};

