/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RoadSideAlert_H_
#define	_RoadSideAlert_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRCmsgID.h"
#include "MsgCount.h"
#include "ITIScodes.h"
#include "MsgCRC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RoadSideAlert */
typedef struct RoadSideAlert {
	DSRCmsgID_t	 msgID;
	MsgCount_t	 msgCnt;
	ITIScodes_t	 typeEvent;
	MsgCRC_t	 crc;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadSideAlert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSideAlert;

#ifdef __cplusplus
}
#endif

#endif	/* _RoadSideAlert_H_ */
